import { expect, test } from '@playwright/test'

test('quality governance happy path remains clickable', async ({ page }) => {
  await page.goto('/overview')
  await expect(page.getByRole('heading', { name: '质量总览', level: 2 })).toBeVisible()
  await page.getByRole('button', { name: /意图一致率|意图一致性|Intent Consistency/ }).click()
  await expect(page).toHaveURL(/\/tasks\?.*metric=intent-consistency/)
  await expect(page.getByRole('row', { name: /根据刚才的销售 Excel/ })).toBeVisible()
  await page.getByRole('row', { name: /根据刚才的销售 Excel/ }).click()
  await expect(page.getByRole('dialog', { name: 'Task 001' })).toBeVisible()
  await page.getByRole('button', { name: /evidence-task-001/ }).first().click()
  await expect(page.getByRole('dialog').filter({ hasText: 'Task Understanding' }).last()).toBeVisible()
  await page.getByRole('button', { name: /Close panel/ }).last().click()
  await page.getByRole('button', { name: 'Close panel' }).click()
  await page.getByRole('navigation', { name: '面包屑导航' }).getByRole('link', { name: 'Task / Trace' }).click()
  await expect(page).toHaveURL(/\/tasks\?.*metric=intent-consistency/)
  await expect(page.getByRole('row', { name: /根据刚才的销售 Excel/ })).toBeVisible()
  await page.goto('/benchmarks')
  await expect(page.getByRole('main').getByRole('heading', { name: 'Benchmark', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: /Regressed Cases/ }).click()
  await expect(page.getByText(/Version B changed a passing outcome/).first()).toBeVisible()
  await page.goto('/performance')
  await page.getByRole('row').nth(1).click()
  await page.getByRole('button', { name: '查看全部异常 Trace' }).click()
  await expect(page).toHaveURL(/\/tasks\?.*anomalyTool=/)
  await expect(page.getByRole('main').getByRole('heading', { name: 'Task / Trace', exact: true })).toBeVisible()
})
