import { ArrowRight, CircleAlert, ShieldAlert, Wrench } from 'lucide-react'
import type { ReactNode } from 'react'
import { useContextNavigation } from './layout'
import { useQuality } from './store'
import { getPerformanceMetrics, getScopeLabel, getToolMetrics } from './selectors'
import { Button, InlineNotice, SectionHeader, StatusBadge, cn } from './ui'

function Kpi({ label, value, note, tone = 'neutral', onClick }: { label: string; value: string; note?: string; tone?: 'neutral' | 'pass' | 'warn' | 'fail'; onClick?: () => void }) {
  const content = <><div className="flex items-start justify-between gap-2"><span className="min-w-0 break-words text-[11px] text-muted">{label}</span>{onClick && <ArrowRight className="h-3.5 w-3.5 shrink-0 text-slate-400" aria-hidden="true" />}</div><div className={cn('mt-2 break-words text-xl font-semibold text-ink', tone === 'pass' && 'text-pass', tone === 'warn' && 'text-warn', tone === 'fail' && 'text-fail')}>{value}</div>{note && <p className="mt-1 break-words text-[10px] leading-4 text-muted">{note}</p>}</>
  return onClick ? <button type="button" onClick={onClick} className="min-w-0 rounded-md border border-line bg-white p-3 text-left transition hover:border-accent/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent">{content}</button> : <div className="min-w-0 rounded-md border border-line bg-white p-3">{content}</div>
}

function Panel({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <section className="rounded-lg border border-line bg-panel p-4 shadow-panel"><SectionHeader eyebrow={eyebrow} title={title} description={description} />{children}</section>
}

export function AnomalyMonitoringPage() {
  const { state } = useQuality()
  const { navigateContext } = useContextNavigation()
  const metrics = getPerformanceMetrics(state, state.filters)
  const tools = getToolMetrics(state, state.filters)
  const openTasks = (metric: string, extra: Record<string, string> = {}) => navigateContext('/tasks', { params: { metric, ...extra } })
  const costValue = metrics.cost.deviation === null ? 'UNKNOWN' : `${metrics.cost.deviation > 0 ? '+' : ''}${metrics.cost.deviation}%`
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><p className="eyebrow">异常监控</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-ink">异常监控</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-muted">聚合响应时间、流式生成、Token/成本、Tool 调用和商业化/风控异常，点击任意异常回到 Task / Trace。</p><p className="mt-2 text-[11px] text-slate-400">{getScopeLabel(state.filters)} · {metrics.taskCount} 个 Query · Mock 数据</p></div><Button icon={ArrowRight} onClick={() => openTasks('risk-interception')}>查看异常任务</Button></div>
    <Panel eyebrow="响应与流式" title="响应与流式" description="总时延效率按平均实际 latency / 平均预期 latency 计算；TTFT 无埋点时不推断状态。">
      <div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="总时延效率" value={metrics.totalLatencyEfficiency.status === 'UNKNOWN' ? 'UNKNOWN' : `${metrics.totalLatencyEfficiency.rate.toFixed(1)}%`} tone={metrics.totalLatencyEfficiency.status === 'FAIL' ? 'warn' : 'pass'} note="<=1 正常 · 1-1.5 可接受 · 1.5-2 低效 · >2 异常" onClick={() => openTasks('latency-efficiency')} /><Kpi label="TTFT" value={metrics.ttft.averageMs === null ? 'UNKNOWN' : `${metrics.ttft.averageMs}ms`} note={metrics.ttft.averageMs === null ? '基线未建立' : `${metrics.ttft.sourceTaskIds.length} 个有埋点任务`} /><Kpi label="模型吞吐量" value={`${metrics.throughput.tokensPerSecond.toLocaleString()} tok/s`} note="总 Token / 模型总耗时" /><Kpi label="监控范围" value={`${metrics.taskCount} 个 Query`} note="当前全局筛选范围" /></div>
      <div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5">{metrics.latencyBands.map((band) => <button key={band.band} type="button" onClick={() => openTasks('latency-band', { latencyBand: band.band })} className="rounded-md border border-line bg-slate-50/70 p-2 text-left hover:border-accent/50"><p className="text-[11px] font-medium text-ink">{band.band}</p><p className="mt-1 text-lg font-semibold text-ink">{band.count}</p><p className="text-[10px] text-muted">{band.rate.toFixed(1)}%</p></button>)}</div>
    </Panel>
    <Panel eyebrow="Token / 缓存 / 成本" title="Token、缓存与成本" description="一期先记录原始 Token 与缓存；成本只对成功/合格产物做评测，基线未建立时显示 UNKNOWN。">
      <div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="输入 Token 数" value={metrics.tokens.input.toLocaleString()} note="系统提示词、上下文历史、用户请求" /><Kpi label="输出 Token 数" value={metrics.tokens.output.toLocaleString()} note={`总计 ${metrics.tokens.total.toLocaleString()}`} /><Kpi label="缓存命中量" value={`${metrics.cache.hits}`} note={`命中率 ${metrics.cache.hitRate.toFixed(1)}% · 未命中 ${metrics.cache.misses}`} /><Kpi label="成本偏离率" value={costValue} tone={metrics.cost.deviation === null ? 'neutral' : metrics.cost.deviation > 0 ? 'warn' : 'pass'} note={metrics.cost.deviation === null ? '同类任务基线未建立' : `成功产物 ${metrics.cost.evaluatedProducts} 个进入分母`} /></div>
      {metrics.cost.deviation === null && <InlineNotice className="mt-3" tone="warn" title="成本基线未建立">失败产物仍保留原始 Token、Model Call 和 Tool Call 记录，但不进入成本评测分母。</InlineNotice>}
    </Panel>
    <Panel eyebrow="调用与一次执行" title="调用与一次执行" description="先展示 Model / Tool / Retry / Loop 原始数据；Retry/Recovery 成功不计入一次执行成功。">
      <div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Model Call 次数" value={`${state.tasks.filter((task) => state.filters.agentVersion === 'All Versions' || task.agentVersion === state.filters.agentVersion).reduce((sum, task) => sum + task.modelCalls, 0)}`} /><Kpi label="Tool Call 次数" value={`${metrics.toolFrequency.calls}`} onClick={() => openTasks('tool-frequency')} /><Kpi label="Retry / Loop" value={`${state.tasks.reduce((sum, task) => sum + task.retryCount, 0)} / ${state.tasks.reduce((sum, task) => sum + task.loopCount, 0)}`} /><Kpi label="一次执行成功率" value={metrics.oneShotSuccess.eligible ? `${metrics.oneShotSuccess.rate.toFixed(1)}%` : 'N/A'} tone={metrics.oneShotSuccess.rate > 80 ? 'pass' : 'warn'} note={`${metrics.oneShotSuccess.successes}/${metrics.oneShotSuccess.eligible} 次有效执行`} onClick={() => openTasks('one-shot-success')} /></div>
      <div className="mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Tool</th><th>调用占比</th><th>调用次数</th><th>失败次数</th><th>一次执行</th><th /></tr></thead><tbody>{tools.map((tool) => <tr key={tool.tool}><td className="font-medium text-ink">{tool.tool}</td><td>{metrics.toolFrequency.calls ? `${((tool.calls / metrics.toolFrequency.calls) * 100).toFixed(1)}%` : '0%'}</td><td>{tool.calls}</td><td className={tool.failed ? 'text-fail' : 'text-pass'}>{tool.failed}</td><td><StatusBadge status={tool.failed ? '需复核' : '稳定'} tone={tool.failed ? 'warn' : 'pass'} /></td><td><button type="button" aria-label={`查看 ${tool.tool} 异常`} onClick={() => openTasks('tool-frequency', { anomalyTool: tool.tool })}><Wrench className="h-4 w-4 text-accent" aria-hidden="true" /></button></td></tr>)}</tbody></table></div>
    </Panel>
    <Panel eyebrow="商业化与风控" title="商业化与风控" description="按总 Query 计算拦截率，并展示标准化原因分布。">
      <div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2"><Kpi label="风控拦截率" value={`${metrics.risk.rate.toFixed(1)}%`} tone={metrics.risk.blocked ? 'fail' : 'pass'} note={`${metrics.risk.blocked} / ${metrics.taskCount} queries`} onClick={() => openTasks('risk-interception')} /><Kpi label="商业化拦截率" value={`${metrics.commercial.rate.toFixed(1)}%`} tone={metrics.commercial.blocked ? 'warn' : 'pass'} note={`${metrics.commercial.blocked} / ${metrics.taskCount} queries`} onClick={() => openTasks('commercial-interception')} /></div>
      <div className="mt-4 grid min-w-0 gap-3 lg:grid-cols-2"><div className="rounded-md border border-line bg-slate-50/60 p-3"><div className="flex items-center gap-2 text-xs font-semibold text-ink"><ShieldAlert className="h-4 w-4 text-fail" aria-hidden="true" />风控拦截原因</div><div className="mt-3 flex flex-wrap gap-2">{Object.entries(metrics.risk.reasons).map(([reason, count]) => <button key={reason} type="button" onClick={() => openTasks('risk-interception', { interceptionReason: reason })} className="rounded-md border border-fail/15 bg-white px-2.5 py-2 text-left text-[11px] hover:border-fail/40"><span className="text-ink">{reason}</span><span className="ml-2 font-semibold text-fail">{count}</span></button>)}</div></div><div className="rounded-md border border-line bg-slate-50/60 p-3"><div className="flex items-center gap-2 text-xs font-semibold text-ink"><CircleAlert className="h-4 w-4 text-warn" aria-hidden="true" />商业化拦截原因</div><div className="mt-3 flex flex-wrap gap-2">{Object.entries(metrics.commercial.reasons).map(([reason, count]) => <button key={reason} type="button" onClick={() => openTasks('commercial-interception', { interceptionReason: reason })} className="rounded-md border border-warn/15 bg-white px-2.5 py-2 text-left text-[11px] hover:border-warn/40"><span className="text-ink">{reason}</span><span className="ml-2 font-semibold text-warn">{count}</span></button>)}</div></div></div>
    </Panel>
  </div>
}
